pool:
  name: Default

stages:
  - stage : "BuildTestEnv"
    jobs:
      - job: "Setup#Docker#image"
        steps:
          - script: echo "Create Test Env"

  - stage : "ExecuteApplicationTestRuns"
    jobs:
      - job: "RunTests"
        timeoutInMinutes: 600
        container:
          image:  podocker86/robot-base-image-new:latest
          volumes:
            - /home/SlbWeCare/_work/2/s/:/automation
            - /home/SlbWeCare/_work/2/s/reports:/automation/reports
        steps:
          - script: ls /automation
          - script: source /home/centos/downloads/env/bin/activate;robot --nostatusrc --variable BROWSER:chrome -v APPLICATION_HOST:equip.stage.shenzyn.com -v APPLICATION_HOST_API:equip-stage-api.shenzyn.com -v BROWSER:chrome --suitestatlevel 2 --outputdir /automation/Results/$(Build.BuildNumber)/  --include Smoke /automation/testsuites
          - task: PublishPipelineArtifact@1
            inputs:
                targetPath: '/home/SlbWeCare/_work/2/s/reports/$(Build.BuildNumber)' # Required
                artifactName: 'RobotResults' # Optional
#           - task: PublishBuildArtifacts@1
#             inputs:
#               pathToPublish: '/home/SlbWeCare/_work/2/s/Results/$(Build.BuildNumber)'
#               artifactName: RunResults
#          - task: PublishHtmlReport@1
#            inputs:
#               testResultsFiles: report.html
#               searchFolder: '/home/SlbWeCare/_work/2/s/Results/$(Build.BuildNumber)/'
#               condition: succeededOrFailed()
#               displayName: 'Publish Test Results output.xml'
#                reportDir: '/home/SlbWeCare/_work/2/s/Results/$(Build.BuildNumber)/report.html'
#             inputs:
#     #testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
#                 testResultsFiles: '/home/SlbWeCare/_work/2/s/Results/$(Build.BuildNumber)/*.*ml' 
    #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
    #mergeTestResults: false # Optional
    #failTaskOnFailedTests: false # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    #publishRunAttachments: true # Optional
